name: id4me_api
description: This library provides the functionalities necessary to implement an ID4me Relying Party in Dart.
version: 1.0.0
author: Daniel Linsenmeier <daniel@ephenodrom.de>
homepage: https://github.com/Ephenodrom/Dart-Id4me-Api
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  basic_utils: ^1.0.8
  logging: ^0.11.3+2
  uuid: ^2.0.1
  jose: ^0.1.2

dev_dependencies:
  test: '>=0.12.42 <2.0.0'

